name: Firestore Seed

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Motivo (opcional)'
        required: false
  schedule:
    - cron: '0 11 * * 1-5' # 08:00 BRT aprox.

permissions:
  contents: read

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: google-github-actions/auth@71f986410dfbc7added4569d411d040a91dc6935 # v2.1.8
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: '20'

      - name: Install backend deps
        run: |
          npm i firebase-admin
      - name: Seed/Migrate Firestore
        env:
          SEED_REASON: ${{ github.event.inputs.reason }}
        run: |
          node scripts/firestore_seed.mjs
          node scripts/firestore_seed.mjs
